### ISSUE TITLE
Need to limit resources used during deployments.

### ISSUE THREAD

**Issue by c1freitas** [InVisionApp/kit-deployer#103]
We seem to have reached a limit with Private Cloud, where during a deployment of `cfprojects` the Controllers are getting overloaded. This is causes scheduling issues as well as DNS error rates to increase significantly. 

Looking through CloudWatch metrics the controller seems to be able to handle:
`2200 requests per min`
Normal operation appears to be about
`  700  requests per min`

Kit appears to be polling every 3 secs for each namespace. The plan is to increase this rate to slow down a number of requests. We also need to add metrics for each request type to data-dog.

1. Add ENV for defining polling rate. Increase to 10sec
1. Add DD metrics for API requests 
1. Benchmark deployments of cfprojects vs other services for api request rates

ELB load for API controller:
<img width="806" alt="screen shot 2017-08-22 at 3 11 03 pm" src="https://user-images.githubusercontent.com/4039561/29589919-3705921a-874c-11e7-8383-e7ad7623d8af.png">

https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LoadBalancers:search=private-cluster-public-api-elb

**Comment by brianhall** [comment]
@c1freitas If these are only spiking during `cfprojects` deployments, maybe we just need to target our optimizations around services that have fast rollbacks enabled? What do you think?

**Comment by c1freitas** [comment]
That might be nice. I would have to check with @chesleybrown to see about targeting a specific type. Maybe we could pass in the polling delay? It would be good to see metrics for the various types of deployments.

**Comment by c1freitas** [comment]
In looking at the timing, it appears the spikes happen for each deployment, not just `cfprojects`.
Metrics around the number of API calls will be important in trying to track down where the increased load is coming from (kit vs k8s)

**Comment by brianhall** [comment]
Hey Ches, a little extra context - this evening during a deployment Juan noticed that the controllers were maxed out. We quickly paused deployments so we could investigate, resulting in this ticket.

I'd like for us to do some research to see if it really is the kit traffic causing this, and then tackle this and get back to a stable state as quickly as possible. Thanks!

**Comment by chesleybrown** [comment]
The good news is we do already have metrics on the number of API request that kit-server makes and also by service.

https://app.datadoghq.com/dash/132876/deploys?live=true&page=0&is_auto=false&from_ts=1503316154238&to_ts=1503488954238&tile_size=s&tpl_var_service=*

<img width="1162" alt="screen shot 2017-08-23 at 9 18 30 am" src="https://user-images.githubusercontent.com/492166/29614273-2ad0465a-87e4-11e7-876c-f5f9038e40c3.png">

It does seem that `cfprojects` and `cfprojects-api` consistently hit around 400 requests during a deploy. But I also see that `surface` has hit 400 too. Generally the number of requests will be determined by how long the deploy takes and how many clusters it's being deployed to.

I think the best and quickest solution right now is to increase the polling. I'll work on making it a configurable ENV var now and I'll default it to 10 seconds.

**Comment by chesleybrown** [comment]
It's worth noting that `fast-rollbacks` vs `rolling-update` should have negligible differences. We make a couple of extra requests before the deployment starts and after the deployment is done when using `fast-rollbacks`. That should be the only real difference between the strategies. They both would have the same amount of polling requests which is what makes up the 99% of API requests made by `kit-server`.

**Comment by chesleybrown** [comment]
This has been deployed. We have noticed a decrease in API requests after increasing the polling to 10. We've also added a monitor to notify us if things exceed our limit.

Going to close this.
