### ISSUE TITLE
Failure deploying job on 1.6 cluster

### ISSUE THREAD

**Issue by chesleybrown** [InVisionApp/kit-deployer#109]
When deploying a `job` to a kubernetes 1.6 cluster we are seeing the following error message. However the job is still successfully deployed. So the assumption is that this is thrown from the health check status checking and this is done using web API requests.

```
[ERROR] LogID: ed8d0c10-16ff-4c97-8739-9815054495cb Task: deploy - kit-deployer - Error: the server could not find the requested resource
```

**Comment by c1freitas** [comment]
I did not test jobs when we rolled out the 1.6.x kubectl upgrade :(

**Comment by brianhall** [comment]
@manute I think this may be related to the issue you saw this evening with migrator, FYI.

**Comment by manute** [comment]
yeah , I think every time `migrator` is going to be deployed we'll  see this issue. 
I can work on it when @chesleybrown is here to ask him some questions.
