### ISSUE TITLE
Auto-retry on failure

### ISSUE THREAD

**Issue by chesleybrown** [InVisionApp/kit-deployer#127]
Deployments can fail for a number of reasons but often a simple retry will resolve it.

We should have a certain number of automatic retries for the following types of failures:

- kubectl API response errors (such as get, delete, list, apply)
- http network request failures
- timeouts

**Comment by erutherford** [comment]
maybe this is included in http network request failures, but when we see DNS lookup failures like `Error: core: getaddrinfo EAI_AGAIN use1-prod-2.k8s-controller.invisionapp.com:443` we should retry again as it was most likely a temporary blip with our DNS query.
